<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Domains\Food\Models\Restaurant;
use Illuminate\Database\Seeder;

final class RestaurantSeeder extends Seeder
{
    public function run(): void
    {
        $restaurants = [
            [
                'name' => 'Итальянская траттория "Дольче Вита"',
                'slug' => 'dolce-vita',
                'description' => 'Аутентичная итальянская кухня с дровяной печью',
                'address' => 'ул. Тверская, д. 7',
                'phone' => '+7 (495) 123-45-67',
                'website' => 'https://dolcevita.ru',
                'cuisine_types' => ['Italian', 'Pizza'],
                'rating' => 4.8,
                'review_count' => 342,
                'min_order_amount' => 500,
                'delivery_time_minutes' => 30,
                'is_open' => true,
                'is_verified' => true,
                'status' => 'active',
                'tags' => ['italian', 'pizza', 'delivery', 'food'],
            ],
            [
                'name' => 'Суши-бар "Токио"',
                'slug' => 'tokyo-sushi',
                'description' => 'Свежий японский риб и роллы',
                'address' => 'Арбат, д. 12',
                'phone' => '+7 (495) 234-56-78',
                'website' => 'https://tokyo-sushi.ru',
                'cuisine_types' => ['Japanese', 'Sushi'],
                'rating' => 4.7,
                'review_count' => 298,
                'min_order_amount' => 800,
                'delivery_time_minutes' => 45,
                'is_open' => true,
                'is_verified' => true,
                'status' => 'active',
                'tags' => ['sushi', 'japanese', 'delivery'],
            ],
            [
                'name' => 'Мексиканская кантина "Эль Мараб"',
                'slug' => 'el-mariachi',
                'description' => 'Традиционная мексиканская кухня с тако и бурито',
                'address' => 'ул. Новый Арбат, д. 15',
                'phone' => '+7 (495) 345-67-89',
                'website' => 'https://el-mariachi.ru',
                'cuisine_types' => ['Mexican', 'Tacos'],
                'rating' => 4.5,
                'review_count' => 176,
                'min_order_amount' => 400,
                'delivery_time_minutes' => 25,
                'is_open' => true,
                'is_verified' => false,
                'status' => 'active',
                'tags' => ['mexican', 'tacos', 'delivery'],
            ],
            [
                'name' => 'Индийский ресторан "Раджа"',
                'slug' => 'raja-indian',
                'description' => 'Острые индийские карри и традиционный хлеб',
                'address' => 'ул. Кутузова, д. 3',
                'phone' => '+7 (495) 456-78-90',
                'website' => 'https://raja-indian.ru',
                'cuisine_types' => ['Indian', 'Curry'],
                'rating' => 4.6,
                'review_count' => 215,
                'min_order_amount' => 600,
                'delivery_time_minutes' => 35,
                'is_open' => true,
                'is_verified' => true,
                'status' => 'active',
                'tags' => ['indian', 'curry', 'spicy'],
            ],
            [
                'name' => 'Бургерная "Гриль Мастер"',
                'slug' => 'grill-master',
                'description' => 'Сочные бургеры из говядины USDA Prime',
                'address' => 'Пушечный пер., д. 2/9',
                'phone' => '+7 (495) 567-89-01',
                'website' => 'https://grillmaster.ru',
                'cuisine_types' => ['Burgers', 'American'],
                'rating' => 4.4,
                'review_count' => 289,
                'min_order_amount' => 350,
                'delivery_time_minutes' => 20,
                'is_open' => true,
                'is_verified' => true,
                'status' => 'active',
                'tags' => ['burgers', 'fast-food'],
            ],
            [
                'name' => 'Таиландская кухня "Сиам"',
                'slug' => 'siam-thai',
                'description' => 'Том ям, пад тай и другие традиционные тайские блюда',
                'address' => 'Каланчевская ул., д. 5',
                'phone' => '+7 (495) 678-90-12',
                'website' => 'https://siam-thai.ru',
                'cuisine_types' => ['Thai', 'Asian'],
                'rating' => 4.7,
                'review_count' => 204,
                'min_order_amount' => 550,
                'delivery_time_minutes' => 40,
                'is_open' => true,
                'is_verified' => true,
                'status' => 'active',
                'tags' => ['thai', 'asian', 'spicy'],
            ],
            [
                'name' => 'Французский ресторан "Ле Корdon Блю"',
                'slug' => 'le-cordon-bleu',
                'description' => 'Классическая французская кухня высокой кухни',
                'address' => 'Большой Дмитровский переулок, д. 7',
                'phone' => '+7 (495) 789-01-23',
                'website' => 'https://lecordonbleu.ru',
                'cuisine_types' => ['French', 'Fine Dining'],
                'rating' => 4.9,
                'review_count' => 156,
                'min_order_amount' => 2000,
                'delivery_time_minutes' => 50,
                'is_open' => true,
                'is_verified' => true,
                'status' => 'active',
                'tags' => ['french', 'fine-dining', 'expensive'],
            ],
            [
                'name' => 'Стейк-хаус "Prime Cuts"',
                'slug' => 'prime-cuts',
                'description' => 'Премиум стейки и мясные деликатесы',
                'address' => 'ул. Охотный ряд, д. 1/3',
                'phone' => '+7 (495) 890-12-34',
                'website' => 'https://primecuts.ru',
                'cuisine_types' => ['Steakhouse', 'Meat'],
                'rating' => 4.8,
                'review_count' => 267,
                'min_order_amount' => 1500,
                'delivery_time_minutes' => 35,
                'is_open' => true,
                'is_verified' => true,
                'status' => 'active',
                'tags' => ['steak', 'meat', 'premium'],
            ],
            [
                'name' => 'Корейская кухня "Сеул Кухня"',
                'slug' => 'seoul-kitchen',
                'description' => 'Кимчи, биббимбап, булгоги и другие корейские деликатесы',
                'address' => 'ул. Капельский пер., д. 1',
                'phone' => '+7 (495) 901-23-45',
                'website' => 'https://seoulkitchen.ru',
                'cuisine_types' => ['Korean', 'Asian'],
                'rating' => 4.6,
                'review_count' => 198,
                'min_order_amount' => 600,
                'delivery_time_minutes' => 30,
                'is_open' => true,
                'is_verified' => true,
                'status' => 'active',
                'tags' => ['korean', 'asian'],
            ],
            [
                'name' => 'Веган кафе "Земля и Небо"',
                'slug' => 'earth-sky-vegan',
                'description' => '100% веганские блюда из органических продуктов',
                'address' => 'ул. Мясницкая, д. 20/2',
                'phone' => '+7 (495) 012-34-56',
                'website' => 'https://earthsky-vegan.ru',
                'cuisine_types' => ['Vegan', 'Healthy'],
                'rating' => 4.5,
                'review_count' => 142,
                'min_order_amount' => 450,
                'delivery_time_minutes' => 25,
                'is_open' => true,
                'is_verified' => true,
                'status' => 'active',
                'tags' => ['vegan', 'organic', 'healthy'],
            ],
        ];

        foreach ($restaurants as $restaurantData) {
            Restaurant::updateOrCreate(
                ['slug' => $restaurantData['slug']],
                array_merge($restaurantData, [
                    'tenant_id' => 1,
                    'correlation_id' => \Illuminate\Support\Str::uuid()->toString(),
                ]),
            );
        }
    }
}
