<?php

declare(strict_types=1);

namespace App\Filament\Tenant\Resources;

use App\Models\Stationery\StationeryGiftSet;
use App\Models\Stationery\StationeryStore;
use App\Models\Stationery\StationeryCategory;
use App\Services\Stationery\StationeryGiftService;
use App\Services\AI\AIStationeryConstructor;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Filament\Notifications\Notification;
use Filament\Tables\Actions\Action;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Str;

/**
 * StationeryGiftSetResource.
 * Management of Stationery Gift Kits (School Start, Office Set, Calligraphy).
 * Integrated with AI Stationery Constructor for automatic matching.
 */
class StationeryGiftSetResource extends Resource
{
    protected static ?string $model = StationeryGiftSet::class;
    protected static ?string $navigationIcon = 'heroicon-o-gift';
    protected static ?string $navigationGroup = 'Stationery Hub';
    protected static ?string $tenantOwnershipRelationshipName = 'store';

    /**
     * Gift Set Form with Theme and Items assembly.
     */
    public static function form(Form $form): Form
    {
        return $form->schema([
            Forms\Components\Split::make([
                Forms\Components\Section::make('Gift Set Fundamentals')->schema([
                    Forms\Components\TextInput::make('name')
                        ->required()
                        ->maxLength(255)
                        ->autofocus()
                        ->placeholder('Premium Calligraphy Set'),

                    Forms\Components\Select::make('store_id')
                        ->relationship('store', 'name')
                        ->required()
                        ->searchable()
                        ->label('Source Store'),

                    Forms\Components\Select::make('category_id')
                        ->relationship('category', 'name')
                        ->required()
                        ->searchable()
                        ->label('Category'),

                    Forms\Components\Select::make('theme')
                        ->options([
                            'school' => 'Back to School',
                            'office' => 'Office Start',
                            'premium' => 'Premium Art & Design',
                            'minimal' => 'Minimalist Workspace',
                            'calligraphy' => 'Calligraphy & Lettering',
                        ])
                        ->required()
                        ->label('Theme'),

                    Forms\Components\RichEditor::make('description')
                        ->columnSpanFull()
                        ->placeholder('Perfect for students or office workers...'),
                ])->columns(2),

                Forms\Components\Section::make('Kitting & Pricing')->schema([
                    Forms\Components\TextInput::make('price_cents')
                        ->numeric()
                        ->prefix('RUB')
                        ->required()
                        ->label('Total Set Price (Cents)'),

                    Forms\Components\Repeater::make('product_ids')
                        ->label('Items included in Set')
                        ->schema([
                            Forms\Components\Select::make('product_id')
                                ->relationship('store.products', 'name')
                                ->required()
                                ->searchable(),
                        ])
                        ->default([])
                        ->required()
                        ->minItems(2),

                    Forms\Components\Toggle::make('is_active')
                        ->default(true)
                        ->onColor('success')
                        ->offColor('danger'),
                ])->columns(1),
            ])->columnSpanFull(),

            Forms\Components\Section::make('AI & Metadata')->schema([
                Forms\Components\TextInput::make('uuid')
                    ->label('GiftSet UUID')
                    ->disabled()
                    ->dehydrated(false)
                    ->placeholder('autogenerated'),

                Forms\Components\TextInput::make('correlation_id')
                    ->label('Correlation ID (Last Change)')
                    ->disabled()
                    ->dehydrated(false)
                    ->placeholder('audit trace...'),

                Forms\Components\Placeholder::make('ai_score_placeholder')
                    ->label('AI Match Probability')
                    ->content(fn ($record) => $record?->correlation_id ?? 'No AI matching performed.'),
            ])->columns(2),
        ]);
    }

    /**
     * Gift Set Table with Kitting Actions.
     */
    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->searchable()
                    ->sortable()
                    ->limit(50),

                Tables\Columns\TextColumn::make('store.name')
                    ->label('Store')
                    ->searchable(),

                Tables\Columns\TextColumn::make('theme')
                    ->badge()
                    ->color(static function ($state): string {
                        return match ($state) {
                            'premium' => 'primary',
                            'office' => 'success',
                            'school' => 'warning',
                            default => 'gray',
                        };
                    })
                    ->sortable()
                    ->formatStateUsing(fn ($state) => Str::headline($state)),

                Tables\Columns\TextColumn::make('price_cents')
                    ->label('Price')
                    ->money('rub', divideBy: 100)
                    ->sortable(),

                Tables\Columns\IconColumn::make('is_active')
                    ->boolean()
                    ->label('Active Status'),

                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('theme'),
                Tables\Filters\TernaryFilter::make('is_active'),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Action::make('ai_validate')
                    ->icon('heroicon-o-sparkles')
                    ->label('AI Match')
                    ->action(function (StationeryGiftSet $record, AIStationeryConstructor $ai) {
                        try {
                            $kit = $ai->constructRecommendedKit($record->theme, 10000);
                            Notification::make()
                                ->title("AI Matching Successful for Theme: {$record->theme}")
                                ->body("Suggested items: " . count($kit))
                                ->success()
                                ->send();
                        } catch (\Throwable $e) {
                            Notification::make()
                                ->title("AI Error: {$e->getMessage()}")
                                ->danger()
                                ->send();
                        }
                    }),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()
            ->with(['store', 'category'])
            ->latest('updated_at');
    }
}
