<?php

declare(strict_types=1);

namespace App\Filament\Tenant\Resources;

use App\Models\Stationery\StationeryCategory;
use App\Models\Stationery\StationeryStore;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Filament\Notifications\Notification;
use Filament\Tables\Actions\Action;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Str;

/**
 * StationeryCategoryResource.
 * Management of Stationery Categories (Pens, Paper, Art Supplies, Desk Organizers).
 * Includes nesting and SEO parameters.
 */
class StationeryCategoryResource extends Resource
{
    protected static ?string $model = StationeryCategory::class;
    protected static ?string $navigationIcon = 'heroicon-o-tag';
    protected static ?string $navigationGroup = 'Stationery Hub';
    protected static ?string $tenantOwnershipRelationshipName = 'store';

    /**
     * Category Form with SEO and Metadata capabilities.
     */
    public static function form(Form $form): Form
    {
        return $form->schema([
            Forms\Components\Split::make([
                Forms\Components\Section::make('Category Discovery')->schema([
                    Forms\Components\TextInput::make('name')
                        ->required()
                        ->maxLength(255)
                        ->autofocus()
                        ->placeholder('Desk Organizers'),

                    Forms\Components\Select::make('store_id')
                        ->relationship('store', 'name')
                        ->required()
                        ->searchable()
                        ->label('Source Store'),

                    Forms\Components\RichEditor::make('description')
                        ->columnSpanFull()
                        ->placeholder('Everything for your workspace organization...'),
                ])->columns(2),

                Forms\Components\Section::make('Metadata & SEO')->schema([
                    Forms\Components\KeyValue::make('metadata')
                        ->label('SEO & Tags (Meta title, Meta description)')
                        ->required(),

                    Forms\Components\Toggle::make('is_active')
                        ->default(true)
                        ->onColor('success')
                        ->offColor('danger'),

                    Forms\Components\FileUpload::make('icon_url')
                        ->label('Category Icon')
                        ->image()
                        ->disk('public')
                        ->directory('stationery/categories'),
                ])->columns(1),
            ])->columnSpanFull(),

            Forms\Components\Section::make('System Scrutiny')->schema([
                Forms\Components\TextInput::make('uuid')
                    ->label('Category UUID')
                    ->disabled()
                    ->dehydrated(false)
                    ->placeholder('autogenerated'),

                Forms\Components\TextInput::make('correlation_id')
                    ->label('Correlation ID (Last Change Trace)')
                    ->disabled()
                    ->dehydrated(false)
                    ->placeholder('audit trace...'),

                Forms\Components\Placeholder::make('products_count')
                    ->label('Active Products in Category')
                    ->content(fn ($record) => $record?->products_count ?? 'Calculating...'),
            ])->columns(2),
        ]);
    }

    /**
     * Category Table with Discovery and Management controls.
     */
    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->searchable()
                    ->sortable()
                    ->limit(50),

                Tables\Columns\TextColumn::make('store.name')
                    ->label('Store')
                    ->searchable(),

                Tables\Columns\TextColumn::make('products_count')
                    ->label('Items')
                    ->numeric()
                    ->counts('products')
                    ->sortable(),

                Tables\Columns\IconColumn::make('is_active')
                    ->boolean()
                    ->label('Active'),

                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                Tables\Filters\TernaryFilter::make('is_active'),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Action::make('bulk_reprice')
                    ->icon('heroicon-o-currency-dollar')
                    ->label('Reprice Category')
                    ->requiresConfirmation()
                    ->action(function (StationeryCategory $record) {
                        Notification::make()
                            ->title("Bulk repricing logic would be triggered here.")
                            ->info()
                            ->send();
                    }),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()
            ->withCount('products')
            ->latest('updated_at');
    }
}
