<?php

declare(strict_types=1);

namespace App\Filament\Tenant\Resources;

use App\Models\Stationery\StationerySubscription;
use App\Models\Stationery\StationeryStore;
use App\Services\Stationery\StationerySubscriptionService;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Filament\Notifications\Notification;
use Filament\Tables\Actions\Action;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\DB;
use App\Models\User;

/**
 * StationerySubscriptionResource.
 * Managing of Recurring Stationery Supplies (Office Boxes, Premium Kit Boxes).
 * Includes Billing Period and Box Type Logic.
 */
class StationerySubscriptionResource extends Resource
{
    protected static ?string $model = StationerySubscription::class;
    protected static ?string $navigationIcon = 'heroicon-o-arrow-path-rounded-square';
    protected static ?string $navigationGroup = 'Stationery Hub';
    protected static ?string $tenantOwnershipRelationshipName = 'store';

    /**
     * Subscription Form with Interval and Tier selection.
     */
    public static function form(Form $form): Form
    {
        return $form->schema([
            Forms\Components\Split::make([
                Forms\Components\Section::make('Subscription Core')->schema([
                    Forms\Components\Select::make('user_id')
                        ->relationship('user', 'name')
                        ->required()
                        ->searchable()
                        ->label('Customer (B2B/B2C)'),

                    Forms\Components\Select::make('store_id')
                        ->relationship('store', 'name')
                        ->required()
                        ->searchable()
                        ->label('Source Store'),

                    Forms\Components\Select::make('box_tier')
                        ->options([
                            'Basic' => 'Basic Office Supplies',
                            'Standard' => 'Standard Corporate Kit',
                            'Premium' => 'Premium Art & Design Box',
                            'Executive' => 'Executive Office Set',
                        ])
                        ->required()
                        ->label('Box Tier'),

                    Forms\Components\Select::make('billing_period')
                        ->options([
                            'monthly' => 'Monthly Billing',
                            'quarterly' => 'Quarterly Billing',
                            'yearly' => 'Yearly Billing (15% Save)',
                        ])
                        ->default('monthly')
                        ->required()
                        ->label('Interval'),

                    Forms\Components\DatePicker::make('next_billing_at')
                        ->required()
                        ->displayFormat('d.m.Y')
                        ->native(false)
                        ->label('Next Run'),
                ])->columns(2),

                Forms\Components\Section::make('Service Parameters')->schema([
                    Forms\Components\TextInput::make('price_cents')
                        ->numeric()
                        ->prefix('RUB')
                        ->required()
                        ->label('Monthly Cost (Cents)'),

                    Forms\Components\KeyValue::make('preferences')
                        ->required()
                        ->label('Box Customization (Colors, Brands, Paper Type)'),

                    Forms\Components\Toggle::make('is_active')
                        ->default(true)
                        ->onColor('success')
                        ->offColor('danger'),
                ])->columns(1),
            ])->columnSpanFull(),

            Forms\Components\Section::make('Audit Details')->schema([
                Forms\Components\TextInput::make('uuid')
                    ->label('Subscription UUID')
                    ->disabled()
                    ->dehydrated(false)
                    ->placeholder('autogenerated'),

                Forms\Components\TextInput::make('correlation_id')
                    ->label('Correlation ID (Last Billing Trace)')
                    ->disabled()
                    ->dehydrated(false)
                    ->placeholder('trace log...'),

                Forms\Components\Placeholder::make('last_payout')
                    ->label('Last Billing History')
                    ->content(fn ($record) => $record?->correlation_id ?? 'No billing events yet.'),
            ])->columns(2),
        ]);
    }

    /**
     * Subscription Table with Billing controls.
     */
    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('user.name')
                    ->label('Customer')
                    ->searchable()
                    ->sortable(),

                Tables\Columns\TextColumn::make('box_tier')
                    ->label('Tier')
                    ->badge()
                    ->color(static function ($state): string {
                        return match ($state) {
                            'Premium' => 'primary',
                            'Executive' => 'success',
                            'Basic' => 'gray',
                            default => 'warning',
                        };
                    })
                    ->sortable(),

                Tables\Columns\TextColumn::make('price_cents')
                    ->label('Monthly')
                    ->money('rub', divideBy: 100)
                    ->sortable(),

                Tables\Columns\TextColumn::make('billing_period')
                    ->label('Billing')
                    ->formatStateUsing(fn ($state) => ucfirst($state)),

                Tables\Columns\TextColumn::make('next_billing_at')
                    ->label('Next Payout')
                    ->date('d.m.Y')
                    ->sortable(),

                Tables\Columns\IconColumn::make('is_active')
                    ->boolean()
                    ->label('Status'),

                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('box_tier')
                    ->options([
                        'Basic' => 'Basic',
                        'Premium' => 'Premium',
                        'Executive' => 'Executive',
                    ]),

                Tables\Filters\TernaryFilter::make('is_active'),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Action::make('process_billing')
                    ->icon('heroicon-o-currency-dollar')
                    ->label('Force Billing')
                    ->requiresConfirmation()
                    ->action(function (StationerySubscription $record, StationerySubscriptionService $service) {
                        try {
                            $service->processMonthlyBilling($record->id);
                            Notification::make()
                                ->title("Billing processed for subscription {$record->id}")
                                ->success()
                                ->send();
                        } catch (\Throwable $e) {
                            Notification::make()
                                ->title("Billing failed: {$e->getMessage()}")
                                ->danger()
                                ->send();
                        }
                    }),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()
            ->with(['user', 'store'])
            ->latest('next_billing_at');
    }
}
