<?php

declare(strict_types=1);

namespace App\Filament\Tenant\Resources;

use App\Domains\Stationery\Models\StationeryCategory;
use App\Domains\Stationery\Models\StationeryStore;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Filament\Notifications\Notification;
use Filament\Tables\Actions\Action;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Str;

/**
 * StationeryCategoryResource.
 * Management of Stationery Categories (Pens, Paper, Art Supplies, Desk Organizers).
 * Includes nesting and SEO parameters.
 */
class StationeryCategoryResource extends Resource
{
    protected static ?string $model = StationeryCategory::class;
    protected static ?string $navigationIcon = 'heroicon-o-tag';
    protected static ?string $navigationGroup = 'Stationery Hub';
    protected static ?string $tenantOwnershipRelationshipName = 'store';

    /**
     * Category Form with SEO and Metadata capabilities.
     */
    public static function form(Form $form): Form
    {
        return $form->schema([
            Forms\Components\Split::make([
                Forms\Components\Section::make('Category Discovery')->schema([
                    Forms\Components\TextInput::make('name')
                        ->required()
                        ->maxLength(255)
                        ->autofocus()
                        ->placeholder('Desk Organizers'),

                    Forms\Components\Select::make('store_id')
                        ->relationship('store', 'name')
                        ->required()
                        ->searchable()
                        ->label('Source Store'),

                    Forms\Components\RichEditor::make('description')
                        ->columnSpanFull()
                        ->placeholder('Everything for your workspace organization...'),
                ])->columns(2),

                Forms\Components\Section::make('Metadata & SEO')->schema([
                    Forms\Components\KeyValue::make('metadata')
                        ->label('SEO & Tags (Meta title, Meta description)')
                        ->required(),

                    Forms\Components\Toggle::make('is_active')
                        ->default(true)
                        ->onColor('success')
                        ->offColor('danger'),

                    Forms\Components\FileUpload::make('icon_url')
                        ->label('Category Icon')
                        ->image()
                        ->disk('public')
                        ->directory('stationery/categories'),
                ])->columns(1),
            ])->columnSpanFull(),

            Forms\Components\Section::make('System Scrutiny')->schema([
                Forms\Components\TextInput::make('uuid')
                    ->label('Category UUID')
                    ->disabled()
                    ->dehydrated(false)
                    ->placeholder('autogenerated'),

                Forms\Components\TextInput::make('correlation_id')
                    ->label('Correlation ID (Last Change Trace)')
                    ->disabled()
                    ->dehydrated(false)
                    ->placeholder('audit trace...'),

                Forms\Components\Placeholder::make('products_count')
                    ->label('Active Products in Category')
                    ->content(fn ($record) => $record?->products_count ?? 'Calculating...'),
            ])->columns(2),
        ]);

    public static function getPages(): array
    {
        return [
            'index' => Pages\\ListStationeryCategory::route('/'),
            'create' => Pages\\CreateStationeryCategory::route('/create'),
            'edit' => Pages\\EditStationeryCategory::route('/{record}/edit'),
            'view' => Pages\\ViewStationeryCategory::route('/{record}'),
        ];

    public static function getPages(): array
    {
        return [
            'index' => Pages\\ListStationeryCategory::route('/'),
            'create' => Pages\\CreateStationeryCategory::route('/create'),
            'edit' => Pages\\EditStationeryCategory::route('/{record}/edit'),
            'view' => Pages\\ViewStationeryCategory::route('/{record}'),
        ];
    }
}
