<?php

declare(strict_types=1);

namespace App\Filament\Tenant\Resources;

use App\Models\Stationery\StationeryStore;
use App\Models\Stationery\StationerySubscription;
use App\Models\Stationery\StationeryGiftSet;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Filament\Notifications\Notification;
use Filament\Tables\Actions\Action;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\DB;
use App\Services\Stationery\StationeryService;

/**
 * StationeryStoreResource.
 * Management of Stationery Stores with tenant scoping.
 * Each Store can handle B2B/B2C catalogs.
 */
class StationeryStoreResource extends Resource
{
    protected static ?string $model = StationeryStore::class;
    protected static ?string $navigationIcon = 'heroicon-o-building-storefront';
    protected static ?string $navigationGroup = 'Stationery Hub';
    protected static ?string $tenantOwnershipRelationshipName = 'tenant';

    /**
     * Store Form with correlation_id and full audit capability.
     */
    public static function form(Form $form): Form
    {
        return $form->schema([
            Forms\Components\Split::make([
                Forms\Components\Section::make('Store Metadata')->schema([
                    Forms\Components\TextInput::make('name')
                        ->required()
                        ->maxLength(255)
                        ->autofocus()
                        ->placeholder('The Pen Shop'),

                    Forms\Components\TextInput::make('address')
                        ->required()
                        ->maxLength(500)
                        ->placeholder('Nevsky Prospekt, 28, St. Petersburg'),

                    Forms\Components\Select::make('tenant_id')
                        ->relationship('tenant', 'name')
                        ->required()
                        ->searchable(),

                    Forms\Components\RichEditor::make('description')
                        ->columnSpanFull()
                        ->placeholder('Official Stationery supply point for B2B/B2C...'),
                ])->columns(2),

                Forms\Components\Section::make('Configuration & Social')->schema([
                    Forms\Components\KeyValue::make('contact_info')
                        ->label('Social Media & Contacts (IG, TG, Phone)')
                        ->required(),

                    Forms\Components\KeyValue::make('metadata')
                        ->label('Store Config (Delivery price, Logo URL)')
                        ->required(),

                    Forms\Components\Toggle::make('is_active')
                        ->default(true)
                        ->onColor('success')
                        ->offColor('danger'),
                ])->columns(1),
            ])->columnSpanFull(),

            Forms\Components\Section::make('System & Safety')->schema([
                Forms\Components\TextInput::make('uuid')
                    ->label('Store UUID')
                    ->disabled()
                    ->dehydrated(false)
                    ->placeholder('autogenerated'),

                Forms\Components\TextInput::make('correlation_id')
                    ->label('Correlation ID (Last Change)')
                    ->disabled()
                    ->dehydrated(false)
                    ->placeholder('audit trace...'),

                Forms\Components\ViewField::make('stats_preview')
                    ->view('filament.components.store-stats-preview')
                    ->columnSpanFull(),
            ])->columns(2),
        ]);
    }

    /**
     * Store Table with deep performance analysis tools.
     */
    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->searchable()
                    ->sortable()
                    ->limit(50),

                Tables\Columns\TextColumn::make('address')
                    ->searchable()
                    ->sortable()
                    ->limit(30),

                Tables\Columns\TextColumn::make('products_count')
                    ->label('Products')
                    ->numeric()
                    ->counts('products')
                    ->sortable(),

                Tables\Columns\TextColumn::make('rating')
                    ->label('Rating')
                    ->numeric(1)
                    ->sortable(),

                Tables\Columns\IconColumn::make('is_active')
                    ->boolean()
                    ->label('Active'),

                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                Tables\Filters\TernaryFilter::make('is_active'),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Action::make('recalculate_inventory')
                    ->icon('heroicon-o-arrow-path')
                    ->label('Audit Stock')
                    ->action(function (StationeryStore $record, StationeryService $service) {
                        // CANON 2026 Audit Logic Placeholder
                        Notification::make()
                            ->title("Auditing system initialized for store {$record->name}")
                            ->success()
                            ->send();
                    }),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()
            ->withCount('products')
            ->latest('updated_at');
    }
}
