<?php
// Simple autoload generator
$classList = [];
$dirs = ["app", "modules", "database/factories", "database/seeders"];

function scanDirectory($dir, $baseNamespace, &$classList) {
    if (!is_dir($dir)) return;
    $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir));
    foreach ($iterator as $file) {
        if ($file->getExtension() === "php") {
            $path = str_replace([$dir . "/", ".php"], "", $file->getPathname());
            $className = str_replace("/", "\\", $path);
            $fullClass = $baseNamespace . $className;
            $classList[$fullClass] = $file->getPathname();
        }
    }
}

scanDirectory("app", "App\\", $classList);
scanDirectory("modules", "Modules\\", $classList);
scanDirectory("database/factories", "Database\\Factories\\", $classList);
scanDirectory("database/seeders", "Database\\Seeders\\", $classList);

$autoloadPsr4 = [
    "App\\" => "app/",
    "Database\\Factories\\" => "database/factories/",
    "Database\\Seeders\\" => "database/seeders/",
    "Modules\\" => "modules/",
];

file_put_contents("vendor/composer/autoload_classmap.php", "<?php\nreturn " . var_export($classList, true) . ";\n");
file_put_contents("vendor/composer/autoload_psr4.php", "<?php\nreturn " . var_export($autoloadPsr4, true) . ";\n");

// Create autoload_real.php
file_put_contents("vendor/composer/autoload_real.php", '<?php
// autoload_real.php @generated by Composer
class ComposerAutoloaderInit
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ("Composer\\Autoload\\ClassLoader" === $class) {
            require __DIR__ . "/ClassLoader.php";
        }
    }

    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array("ComposerAutoloaderInit", "loadClassLoader"), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(dirname(__DIR__));
        spl_autoload_unregister(array("ComposerAutoloaderInit", "loadClassLoader"));

        $useStaticLoader = PHP_VERSION_ID >= 50600 && !defined("HHVM_VERSION") && (!function_exists("zend_loader_file_encoded") || !zend_loader_file_encoded());
        if ($useStaticLoader) {
            require_once __DIR__ . "/autoload_static.php";
            call_user_func(\Composer\Autoload\ComposerStaticInit::getInitializer($loader));
        } else {
            $map = require __DIR__ . "/autoload_namespaces.php";
            foreach ($map as $namespace => $path) {
                $loader->set($namespace, $path);
            }

            $map = require __DIR__ . "/autoload_psr4.php";
            foreach ($map as $namespace => $path) {
                $loader->setPsr4($namespace, $path);
            }

            $classMap = require __DIR__ . "/autoload_classmap.php";
            if ($classMap) {
                $loader->addClassMap($classMap);
            }
        }

        $loader->register(true);

        if ($useStaticLoader) {
            $includeFiles = Composer\Autoload\ComposerStaticInit::$files;
        } else {
            $includeFiles = require __DIR__ . "/autoload_files.php";
        }
        foreach ($includeFiles as $fileIdentifier => $file) {
            composerRequire($fileIdentifier, $file);
        }

        return $loader;
    }
}

function composerRequire($fileIdentifier, $file)
{
    if (empty($GLOBALS["__composer_autoload_files"][$fileIdentifier])) {
        require $file;
        $GLOBALS["__composer_autoload_files"][$fileIdentifier] = true;
    }
}
');

echo "Autoload files regenerated\n";
