echo "📝 PUSH GIT REPO - GENERATE YOUR TOKEN FIRST!"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "✨ STEP 1: Generate Personal Access Token (PAT)"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1. Open this link:"
echo "   https://github.com/settings/tokens/new"
echo ""
echo "2. Fill in:"
echo "   • Token name: CatVRF-Deploy-Token"
echo "   • Expiration: 90 days"
echo "   • Scopes: repo, workflow, admin:repo_hook"
echo ""
echo "3. Click 'Generate token' and COPY it"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "✨ STEP 2: Store Token in PowerShell"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "$env:GITHUB_TOKEN = 'ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxx'"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "✨ STEP 3: Push to GitHub"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Run this command:"
echo 'git push https://dusannmak1:$env:GITHUB_TOKEN@github.com/dusannmak1/CatVRF.git main'
echo ""
echo "Or use:"
echo "git config credential.helper store"
echo "git push -u origin main"
echo "(Then enter token when prompted)"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "✨ Repository Info"
echo "════════════════════════════════════════════════════════════"
echo "URL: https://github.com/dusannmak1/CatVRF"
echo "Status: Private ✅"
echo "Branches: main"
echo "Ready to deploy: YES ✅"
echo ""
