# Обновить все 56 Policy файлов на BaseSecurityPolicy

$policiesDir = "c:\opt\kotvrf\CatVRF\app\Policies"
$policyFiles = @(
    "AdCampaignPolicy.php",
    "AlertPolicy.php",
    "AnalyticsPolicy.php",
    "AttendancePolicy.php",
    "AutomotivePolicy.php",
    "B2BPartnerPolicy.php",
    "BoardinghousePolicy.php",
    "BusinessGroupPolicy.php",
    "ContractPolicy.php",
    "CountryEstatePolicy.php",
    "CouponPolicy.php",
    "CoursePolicy.php",
    "CustomerAccountPolicy.php",
    "CustomerAddressPolicy.php",
    "CustomerPolicy.php",
    "CustomerReviewPolicy.php",
    "CustomerWishlistPolicy.php",
    "DailyApartmentPolicy.php",
    "DeliveryOrderPolicy.php",
    "DiscountPolicy.php",
    "DomainPolicy.php",
    "EmployeePolicy.php",
    "EventPolicy.php",
    "FoodOrderPolicy.php",
    "GeoZonePolicy.php",
    "HotelBookingPolicy.php",
    "HRExchangeTaskPolicy.php",
    "HRJobVacancyPolicy.php",
    "InsurancePolicyPolicy.php",
    "InventoryItemPolicy.php",
    "InventoryPolicy.php",
    "InvoicePolicy.php",
    "LeaveRequestPolicy.php",
    "MarketplaceProductPolicy.php",
    "MarketplaceServicePolicy.php",
    "MedicalCardPolicy.php",
    "MessagePolicy.php",
    "NewsletterPolicy.php",
    "NotificationPolicy.php",
    "OrderPolicy.php",
    "PaymentTransactionPolicy.php",
    "PayrollPolicy.php",
    "PayrollRunPolicy.php",
    "ProductPolicy.php",
    "PropertyPolicy.php",
    "ReportPolicy.php",
    "RestaurantMenuItemPolicy.php",
    "SalonPolicy.php",
    "SportsMembershipPolicy.php",
    "SupplierPolicy.php",
    "TaxiRidePolicy.php",
    "TeamPolicy.php",
    "TriggerPolicy.php",
    "WalletPolicy.php"
)

Write-Host "✅ Total policies to update: $($policyFiles.Count)"
