// CRM & Tender
export { default as crmApi } from './crmApi'
export { default as tenderApi } from './tenderApi'
export { default as supermarketApi } from './supermarketApi'

// B2B APIs
export { default as restaurantB2bApi } from './restaurantB2bApi'
export { default as autoB2bApi } from './autoB2bApi'
export { default as beautyB2bApi } from './beautyB2bApi'
export { default as dentalB2bApi } from './dentalB2bApi'
export { default as fashionB2bApi } from './fashionB2bApi'
export { default as flowersB2bApi } from './flowersB2bApi'
export { default as hotelsB2bApi } from './hotelsB2bApi'
export { default as realestateB2bApi } from './realestateB2bApi'
export { default as logisticsB2bApi } from './logisticsB2bApi'
export { default as constructionB2bApi } from './constructionB2bApi'
export { default as electronicsB2bApi } from './electronicsB2bApi'
export { default as medicalB2bApi } from './medicalB2bApi'
export { default as pharmacyB2bApi } from './pharmacyB2bApi'
export { default as foodB2bApi } from './foodB2bApi'
export { default as groceryB2bApi } from './groceryB2bApi'
export { default as officecateringB2bApi } from './officecateringB2bApi'
export { default as staffB2bApi } from './staffB2bApi'
export { default as legalB2bApi } from './legalB2bApi'
