<?php declare(strict_types=1);

namespace App\Filament\Tenant\Resources\Party;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

final class PartyThemeResource extends Model
{
    use HasFactory;

    // TODO: Проверить и восстановить содержимое класса, если оно было утеряно
    protected static ?string $model = PartyTheme::class;

        protected static ?string $navigationIcon = 'heroicon-o-sparkles';
        protected static ?string $navigationGroup = 'Party Supplies';
        protected static ?int $navigationSort = 2;

        public static function form(Form $form): Form
        {
            return $form->schema([
                TextInput::make('name')
                    ->required()
                    ->maxLength(100)
                    ->suffix(' theme'),

                Select::make('party_category_id')
                    ->relationship('category', 'name')
                    ->searchable()
                    ->preload()
                    ->required(),

                Textarea::make('description')
                    ->placeholder('Describe the visual atmosphere')
                    ->columnSpanFull(),

                ColorPicker::make('primary_color_hex')
                    ->label('Theme Branding Color')
                    ->default('#ffffff'),

                Toggle::make('is_seasonal')
                    ->label('Seasonal Collection')
                    ->reactive(),

                TextInput::make('season_name')
                    ->label('Season (e.g., Summer 2026)')
                    ->placeholder('Fall / Winter / Spring')
                    ->visible(fn ($get) => $get('is_seasonal')),

                TextInput::make('correlation_id')
                    ->disabled()
                    ->placeholder('Generated by system')
                    ->visible(fn ($record) => $record !== null),
            ]);
        }

        public static function table(Table $table): Table
        {
            return $table
                ->columns([
                    TextColumn::make('name')
                        ->searchable()
                        ->sortable()
                        ->weight('bold'),

                    TextColumn::make('category.name')
                        ->label('Category')
                        ->badge()
                        ->searchable(),

                    ColorColumn::make('primary_color_hex')
                        ->label('Color'),

                    IconColumn::make('is_seasonal')
                        ->boolean()
                        ->label('Seasonal'),

                    TextColumn::make('season_name')
                        ->label('Period')
                        ->color('info')
                        ->wrap(),

                    TextColumn::make('created_at')
                        ->dateTime()
                        ->sortable()
                        ->toggleable(isToggledHiddenByDefault: true),
                ])
                ->filters([
                    // Filter for seasonal themes
                    \Filament\Tables\Filters\TernaryFilter::make('is_seasonal'),

                    // Filter by category
                    \Filament\Tables\Filters\SelectFilter::make('party_category_id')
                        ->label('Event Category')
                        ->relationship('category', 'name'),
                ])
                ->actions([
                    EditAction::make(),
                ])
                ->bulkActions([
                    DeleteBulkAction::make(),
                ]);
        }

        public static function getEloquentQuery(): Builder
        {
            return parent::getEloquentQuery()
                ->with('category')
                ->orderBy('is_seasonal', 'desc')
                ->orderBy('name');
        }

        public static function getPages(): array
        {
            return [
                'index' => \App\Filament\Tenant\Resources\Party\Pages\ListPartyThemes::route('/'),
                'create' => \App\Filament\Tenant\Resources\Party\Pages\CreatePartyTheme::route('/create'),
                'edit' => \App\Filament\Tenant\Resources\Party\Pages\EditPartyTheme::route('/{record}/edit'),
            ];
        }
}
