<?php

declare(strict_types=1);

namespace App\DTOs\Staff;

/**
 * StaffResponseDTO — DTO для ответа с данными сотрудника.
 * CatVRF 2026 — PRODUCTION MANDATORY.
 *
 * Immutable DTO для возврата данных сотрудника в API.
 */
final readonly class StaffResponseDTO
{
    public function __construct(
        public int $id,
        public string $uuid,
        public string $fullName,
        public string $firstName,
        public string $lastName,
        public ?string $middleName = null,
        public ?string $email = null,
        public ?string $phone = null,
        public ?string $telegram = null,
        public ?string $whatsapp = null,
        public ?string $photoUrl = null,
        public string $role,
        public ?string $position = null,
        public ?string $department = null,
        public ?int $managerId = null,
        public ?string $managerName = null,
        public ?string $hiredAt = null,
        public ?string $probationEndAt = null,
        public ?string $employmentType = null,
        public ?string $schedule = null,
        public float $salary,
        public string $salaryType,
        public string $status,
        public ?array $permissions = null,
        public ?int $userId = null,
        // Statistics
        public int $totalOrdersProcessed = 0,
        public float $totalRevenueGenerated = 0,
        public float $averageOrderValue = 0,
        public int $totalCustomersServed = 0,
        public float $customerSatisfactionScore = 0,
        public int $positiveReviews = 0,
        public int $negativeReviews = 0,
        public int $complaints = 0,
        public int $compliments = 0,
        public int $tasksCompleted = 0,
        public int $tasksOverdue = 0,
        public float $taskCompletionRate = 0,
        public int $attendanceDays = 0,
        public int $absenceDays = 0,
        public float $attendanceRate = 0,
        public int $salesCount = 0,
        public float $conversionRate = 0,
        public float $upsellRate = 0,
        public float $crossSellRate = 0,
        public float $qualityScore = 0,
        public float $speedScore = 0,
        public float $accuracyScore = 0,
        public float $efficiencyScore = 0,
        public float $averageProductRating = 0,
        public int $productsRated = 0,
        public ?string $createdAt = null,
        public ?string $updatedAt = null,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            uuid: $data['uuid'],
            fullName: $data['full_name'] ?? $data['fullName'] ?? '',
            firstName: $data['first_name'] ?? $data['firstName'] ?? '',
            lastName: $data['last_name'] ?? $data['lastName'] ?? '',
            middleName: $data['middle_name'] ?? $data['middleName'] ?? null,
            email: $data['email'] ?? null,
            phone: $data['phone'] ?? null,
            telegram: $data['telegram'] ?? null,
            whatsapp: $data['whatsapp'] ?? null,
            photoUrl: $data['photo_url'] ?? $data['photoUrl'] ?? null,
            role: $data['role'] ?? 'employee',
            position: $data['position'] ?? null,
            department: $data['department'] ?? null,
            managerId: $data['manager_id'] ?? $data['managerId'] ?? null,
            managerName: $data['manager_name'] ?? $data['managerName'] ?? null,
            hiredAt: $data['hired_at'] ?? $data['hiredAt'] ?? null,
            probationEndAt: $data['probation_end_at'] ?? $data['probationEndAt'] ?? null,
            employmentType: $data['employment_type'] ?? $data['employmentType'] ?? null,
            schedule: $data['schedule'] ?? null,
            salary: (float) ($data['salary'] ?? 0) / 100,
            salaryType: $data['salary_type'] ?? $data['salaryType'] ?? 'monthly',
            status: $data['status'] ?? 'active',
            permissions: $data['permissions'] ?? null,
            userId: $data['user_id'] ?? $data['userId'] ?? null,
            totalOrdersProcessed: $data['total_orders_processed'] ?? $data['totalOrdersProcessed'] ?? 0,
            totalRevenueGenerated: (float) (($data['total_revenue_generated'] ?? $data['totalRevenueGenerated'] ?? 0) / 100),
            averageOrderValue: (float) (($data['average_order_value'] ?? $data['averageOrderValue'] ?? 0) / 100),
            totalCustomersServed: $data['total_customers_served'] ?? $data['totalCustomersServed'] ?? 0,
            customerSatisfactionScore: (float) ($data['customer_satisfaction_score'] ?? $data['customerSatisfactionScore'] ?? 0),
            positiveReviews: $data['positive_reviews'] ?? $data['positiveReviews'] ?? 0,
            negativeReviews: $data['negative_reviews'] ?? $data['negativeReviews'] ?? 0,
            complaints: $data['complaints'] ?? 0,
            compliments: $data['compliments'] ?? 0,
            tasksCompleted: $data['tasks_completed'] ?? $data['tasksCompleted'] ?? 0,
            tasksOverdue: $data['tasks_overdue'] ?? $data['tasksOverdue'] ?? 0,
            taskCompletionRate: (float) ($data['task_completion_rate'] ?? $data['taskCompletionRate'] ?? 0),
            attendanceDays: $data['attendance_days'] ?? $data['attendanceDays'] ?? 0,
            absenceDays: $data['absence_days'] ?? $data['absenceDays'] ?? 0,
            attendanceRate: (float) ($data['attendance_rate'] ?? $data['attendanceRate'] ?? 0),
            salesCount: $data['sales_count'] ?? $data['salesCount'] ?? 0,
            conversionRate: (float) ($data['conversion_rate'] ?? $data['conversionRate'] ?? 0),
            upsellRate: (float) ($data['upsell_rate'] ?? $data['upsellRate'] ?? 0),
            crossSellRate: (float) ($data['cross_sell_rate'] ?? $data['crossSellRate'] ?? 0),
            qualityScore: (float) ($data['quality_score'] ?? $data['qualityScore'] ?? 0),
            speedScore: (float) ($data['speed_score'] ?? $data['speedScore'] ?? 0),
            accuracyScore: (float) ($data['accuracy_score'] ?? $data['accuracyScore'] ?? 0),
            efficiencyScore: $data['efficiency_score'] ?? $data['efficiencyScore'] ?? 0,
            averageProductRating: (float) ($data['average_product_rating'] ?? $data['averageProductRating'] ?? 0),
            productsRated: $data['products_rated'] ?? $data['productsRated'] ?? 0,
            createdAt: $data['created_at'] ?? $data['createdAt'] ?? null,
            updatedAt: $data['updated_at'] ?? $data['updatedAt'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'uuid' => $this->uuid,
            'full_name' => $this->fullName,
            'first_name' => $this->firstName,
            'last_name' => $this->lastName,
            'middle_name' => $this->middleName,
            'email' => $this->email,
            'phone' => $this->phone,
            'telegram' => $this->telegram,
            'whatsapp' => $this->whatsapp,
            'photo_url' => $this->photoUrl,
            'role' => $this->role,
            'position' => $this->position,
            'department' => $this->department,
            'manager_id' => $this->managerId,
            'manager_name' => $this->managerName,
            'hired_at' => $this->hiredAt,
            'probation_end_at' => $this->probationEndAt,
            'employment_type' => $this->employmentType,
            'schedule' => $this->schedule,
            'salary' => $this->salary,
            'salary_type' => $this->salaryType,
            'status' => $this->status,
            'permissions' => $this->permissions,
            'user_id' => $this->userId,
            'total_orders_processed' => $this->totalOrdersProcessed,
            'total_revenue_generated' => $this->totalRevenueGenerated,
            'average_order_value' => $this->averageOrderValue,
            'total_customers_served' => $this->totalCustomersServed,
            'customer_satisfaction_score' => $this->customerSatisfactionScore,
            'positive_reviews' => $this->positiveReviews,
            'negative_reviews' => $this->negativeReviews,
            'complaints' => $this->complaints,
            'compliments' => $this->compliments,
            'tasks_completed' => $this->tasksCompleted,
            'tasks_overdue' => $this->tasksOverdue,
            'task_completion_rate' => $this->taskCompletionRate,
            'attendance_days' => $this->attendanceDays,
            'absence_days' => $this->absenceDays,
            'attendance_rate' => $this->attendanceRate,
            'sales_count' => $this->salesCount,
            'conversion_rate' => $this->conversionRate,
            'upsell_rate' => $this->upsellRate,
            'cross_sell_rate' => $this->crossSellRate,
            'quality_score' => $this->qualityScore,
            'speed_score' => $this->speedScore,
            'accuracy_score' => $this->accuracyScore,
            'efficiency_score' => $this->efficiencyScore,
            'average_product_rating' => $this->averageProductRating,
            'products_rated' => $this->productsRated,
            'created_at' => $this->createdAt,
            'updated_at' => $this->updatedAt,
        ];
    }
}
