<?php declare(strict_types=1);

return [
    // ML Model configuration
    'ml' => [
        'fraud' => [
            'enabled' => true,
            'model_path' => storage_path('models/fraud'),
            'recalculate_interval' => 'daily',
            'recalculate_time' => '03:00',
            'min_accuracy' => 0.92,
            'min_precision' => 0.85,
            'min_recall' => 0.70,
        ],
    ],

    // Fraud thresholds by operation type
    'thresholds' => [
        'payment_init' => 0.75,
        'card_bind' => 0.80,
        'payout' => 0.85,
        'rating_submit' => 0.70,
        'referral_claim' => 0.65,
        'promo_apply' => 0.60,
        'order_create' => 0.65,
    ],

    // Fallback rules when ML is unavailable
    'fallback_rules' => [
        'max_operations_per_minute' => 5,
        'max_operations_per_hour' => 100,
        'max_amount_per_day' => 1000000, // 10,000 rubles
        'max_card_bind_attempts_per_hour' => 3,
        'device_change_threshold' => 3, // blocks if 3+ devices in 24h
    ],

    // Feature engineering
    'features' => [
        'behavioral' => [
            'operation_count_1m',
            'operation_count_5m',
            'operation_count_15m',
            'operation_count_1h',
            'operation_sum_1d',
            'operation_sum_7d',
            'operation_sum_30d',
            'failed_payments_count_7d',
            'chargebacks_count_30d',
            'account_age_days',
            'successful_payments_count',
        ],
        'geographic' => [
            'geo_distance_from_last',
            'country_change_24h',
            'city_change_24h',
            'timezone_change',
        ],
        'device' => [
            'device_age_days',
            'device_changes_24h',
            'device_changes_7d',
            'browser_agent_hash',
            'ip_reputation_score',
        ],
        'contextual' => [
            'hour_of_day',
            'day_of_week',
            'is_holiday',
            'operation_type_code',
        ],
    ],

    // Monitoring and alerting
    'monitoring' => [
        'alert_threshold' => 100, // alerts if >100 blocks per hour
        'daily_report_time' => '09:00',
        'sentry_enabled' => true,
        'log_channel' => 'fraud_alert',
    ],

    // Velocity limits by operation type
    'velocity_limits' => [
        'payment_init' => 10,
        'card_bind' => 5,
        'payout' => 3,
        'referral_claim' => 20,
        'ai_diagnosis' => 30,
        'slot_hold' => 10,
        'appointment_booking' => 5,
        'default' => 10,
    ],

    // ML inference configuration
    'ml_inference' => [
        'onnx_enabled' => env('FRAUD_ML_ONNX_ENABLED', false),
        'onnx_endpoint' => env('FRAUD_ML_ONNX_ENDPOINT', 'http://localhost:8000/predict'),
        'http_endpoint' => env('FRAUD_ML_HTTP_ENDPOINT'),
        'api_key' => env('FRAUD_ML_API_KEY'),
        'timeout' => env('FRAUD_ML_TIMEOUT', 2),
    ],

    // Circuit breaker configuration
    'circuit_breaker' => [
        'failure_threshold' => 5,
        'timeout_seconds' => 300,
        'half_open_attempts' => 3,
    ],

    // Atomic lock configuration
    'atomic_lock' => [
        'lock_ttl' => 30,
        'slot_hold_ttl' => 300,
    ],

    // Telemetry configuration
    'telemetry' => [
        'enabled' => env('FRAUD_TELEMETRY_ENABLED', true),
        'metrics_ttl' => 86400,
        'prometheus_endpoint' => env('FRAUD_PROMETHEUS_ENDPOINT', '/metrics/fraud'),
    ],

    // Data anonymization configuration (152-ФЗ compliance)
    'anonymization' => [
        'enabled' => env('FRAUD_ANONYMIZATION_ENABLED', true),
        'mask_pattern' => '***',
        'preserve_email_domain' => true,
        'preserve_phone_last_digits' => 4,
        'preserve_card_last_digits' => 4,
    ],

    // Cache configuration
    'cache' => [
        'profile_ttl' => 3600,
        'model_version_ttl' => 3600,
        'use_tags' => true,
    ],

    // Feature drift detection configuration
    'drift_detection' => [
        'enabled' => env('FRAUD_DRIFT_DETECTION_ENABLED', true),
        'check_interval_hours' => 24,
        'min_samples_for_drift_check' => 100,
        'alert_on_drift' => true,
        'auto_rollback_on_drift' => false, // Requires manual approval
        'reference_storage_ttl' => 86400, // 24 hours in Redis
    ],

    // Feature drift thresholds per-vertical
    'drift_thresholds' => [
        'default' => [
            'psi_critical' => 0.25,
            'psi_moderate' => 0.1,
            'ks_critical' => 0.1,
            'ks_moderate' => 0.05,
        ],
        // Medical vertical requires stricter thresholds (152-ФЗ compliance)
        'medical' => [
            'psi_critical' => 0.15,
            'psi_moderate' => 0.08,
            'ks_critical' => 0.07,
            'ks_moderate' => 0.03,
        ],
        'healthcare' => [
            'psi_critical' => 0.15,
            'psi_moderate' => 0.08,
            'ks_critical' => 0.07,
            'ks_moderate' => 0.03,
        ],
        // Financial verticals also stricter
        'payment' => [
            'psi_critical' => 0.18,
            'psi_moderate' => 0.09,
            'ks_critical' => 0.08,
            'ks_moderate' => 0.04,
        ],
        'payout' => [
            'psi_critical' => 0.18,
            'psi_moderate' => 0.09,
            'ks_critical' => 0.08,
            'ks_moderate' => 0.04,
        ],
    ],

    // Top features to monitor for drift (priority order)
    'monitored_features' => [
        'ai_diagnosis_frequency',
        'quota_usage_ratio',
        'geo_anomaly_score',
        'operation_count_1h',
        'operation_count_24h',
        'operation_sum_7d',
        'operation_sum_30d',
        'failed_payments_count_7d',
        'account_age_days',
        'device_changes_24h',
        'geo_distance_from_last',
        'hour_of_day',
        'day_of_week',
        'is_new_device',
        'velocity_5m',
        'velocity_15m',
        'country_change_24h',
        'city_change_24h',
        'timezone_change',
        'ip_reputation_score',
        'browser_agent_hash',
    ],

    // Per-vertical monitored features for drift detection
    'drift_detection_monitored_features' => [
        'medical' => [
            'ai_diagnosis_frequency',
            'health_score_spike',
            'emergency_event_rate',
            'symptom_complexity',
            'consultation_duration',
            'user_age_distribution',
            'diagnosis_confidence',
            'treatment_recommendation_count',
        ],
        'healthcare' => [
            'health_score_prediction_accuracy',
            'lifestyle_data_completeness',
            'lab_result_frequency',
            'preventive_recommendation_rate',
            'risk_factor_detection',
        ],
        'payment' => [
            'payment_amount_distribution',
            'payment_method_usage',
            'transaction_frequency',
            'currency_distribution',
            'merchant_category_distribution',
            'success_rate',
        ],
        'payout' => [
            'payout_amount_distribution',
            'beneficiary_geographic_distribution',
            'payout_frequency',
            'currency_distribution',
            'verification_rate',
        ],
        'beauty' => [
            'service_type_distribution',
            'booking_frequency',
            'price_range_distribution',
            'service_duration',
            'customer_segment_distribution',
        ],
        'food' => [
            'order_size_distribution',
            'restaurant_category_distribution',
            'delivery_time_distribution',
            'order_frequency',
            'menu_item_popularity',
        ],
        'travel' => [
            'booking_lead_time',
            'destination_distribution',
            'travel_duration',
            'price_sensitivity',
            'seasonal_demand',
        ],
        'auto' => [
            'vehicle_type_distribution',
            'service_type_distribution',
            'price_range_distribution',
            'booking_frequency',
            'geographic_distribution',
        ],
        'hotels' => [
            'room_type_distribution',
            'booking_duration',
            'price_per_night_distribution',
            'occupancy_rate',
            'guest_origin_distribution',
        ],
        'fashion' => [
            'product_category_distribution',
            'price_point_distribution',
            'size_distribution',
            'color_preference',
            'brand_affinity',
        ],
        'electronics' => [
            'product_category_distribution',
            'price_range_distribution',
            'brand_distribution',
            'accessory_purchase_rate',
            'upgrade_frequency',
        ],
        'fitness' => [
            'workout_type_distribution',
            'session_duration',
            'membership_tier_distribution',
            'attendance_frequency',
            'trainer_preference',
        ],
        'sports' => [
            'sport_type_distribution',
            'equipment_category_distribution',
            'skill_level_distribution',
            'event_participation_rate',
            'team_size_distribution',
        ],
        'luxury' => [
            'product_category_distribution',
            'price_point_distribution',
            'brand_exclusivity',
            'purchase_frequency',
            'customer_lifetime_value',
        ],
        'insurance' => [
            'policy_type_distribution',
            'coverage_amount_distribution',
            'risk_category_distribution',
            'claim_frequency',
            'premium_payment_pattern',
        ],
        'legal' => [
            'case_type_distribution',
            'service_complexity',
            'hourly_rate_distribution',
            'case_duration',
            'client_industry_distribution',
        ],
        'logistics' => [
            'shipment_size_distribution',
            'route_distance_distribution',
            'delivery_time_distribution',
            'carrier_preference',
            'geographic_coverage',
        ],
        'education' => [
            'course_category_distribution',
            'enrollment_duration',
            'price_point_distribution',
            'completion_rate',
            'student_demographics',
        ],
        'crm' => [
            'lead_source_distribution',
            'deal_size_distribution',
            'sales_cycle_duration',
            'conversion_rate',
            'customer_segment_distribution',
        ],
        'delivery' => [
            'delivery_time_distribution',
            'package_size_distribution',
            'delivery_method_distribution',
            'geographic_distribution',
            'success_rate',
        ],
        'analytics' => [
            'query_complexity_distribution',
            'data_volume_distribution',
            'report_frequency',
            'metric_category_distribution',
            'user_role_distribution',
        ],
        'consulting' => [
            'service_type_distribution',
            'hourly_rate_distribution',
            'project_duration',
            'industry_focus_distribution',
            'team_size_distribution',
        ],
        'content' => [
            'content_type_distribution',
            'engagement_metrics_distribution',
            'publishing_frequency',
            'topic_distribution',
            'audience_segment_distribution',
        ],
        'freelance' => [
            'skill_category_distribution',
            'hourly_rate_distribution',
            'project_duration_distribution',
            'client_rating_distribution',
            'completion_rate',
        ],
        'event_planning' => [
            'event_type_distribution',
            'guest_count_distribution',
            'budget_range_distribution',
            'venue_type_distribution',
            'service_category_distribution',
        ],
        'staff' => [
            'skill_category_distribution',
            'hourly_rate_distribution',
            'availability_pattern',
            'certification_level',
            'industry_experience',
        ],
        'inventory' => [
            'product_category_distribution',
            'stock_level_distribution',
            'turnover_rate',
            'reorder_frequency',
            'supplier_distribution',
        ],
        'taxi' => [
            'trip_distance_distribution',
            'trip_duration_distribution',
            'fare_amount_distribution',
            'pickup_location_distribution',
            'time_of_day_distribution',
        ],
        'tickets' => [
            'event_category_distribution',
            'price_range_distribution',
            'seat_preference_distribution',
            'purchase_lead_time',
            'group_size_distribution',
        ],
        'wallet' => [
            'balance_distribution',
            'transaction_frequency',
            'transaction_type_distribution',
            'currency_distribution',
            'user_segment_distribution',
        ],
        'pet' => [
            'pet_type_distribution',
            'service_category_distribution',
            'breed_distribution',
            'age_distribution',
            'price_range_distribution',
        ],
        'wedding_planning' => [
            'service_category_distribution',
            'budget_range_distribution',
            'guest_count_distribution',
            'venue_type_distribution',
            'season_preference',
        ],
        'veterinary' => [
            'service_type_distribution',
            'pet_type_distribution',
            'treatment_category_distribution',
            'visit_frequency',
            'diagnosis_distribution',
        ],
        'toys_and_games' => [
            'product_category_distribution',
            'age_range_distribution',
            'price_point_distribution',
            'brand_distribution',
            'seasonal_demand',
        ],
        'advertising' => [
            'ad_format_distribution',
            'campaign_budget_distribution',
            'target_audience_segment',
            'ctr_distribution',
            'conversion_rate',
        ],
        'car_rental' => [
            'vehicle_type_distribution',
            'rental_duration_distribution',
            'price_per_day_distribution',
            'geographic_distribution',
            'insurance_option_rate',
        ],
        'finances' => [
            'account_type_distribution',
            'transaction_volume_distribution',
            'balance_distribution',
            'investment_category_distribution',
            'risk_profile_distribution',
        ],
        'flowers' => [
            'flower_type_distribution',
            'occasion_distribution',
            'price_range_distribution',
            'delivery_distance_distribution',
            'seasonal_demand',
        ],
        'furniture' => [
            'product_category_distribution',
            'price_point_distribution',
            'room_type_distribution',
            'material_preference',
            'delivery_distance_distribution',
        ],
        'pharmacy' => [
            'medication_category_distribution',
            'prescription_vs_ocr_ratio',
            'price_range_distribution',
            'brand_vs_generic_ratio',
            'dispensing_frequency',
        ],
        'photography' => [
            'service_type_distribution',
            'session_duration_distribution',
            'price_point_distribution',
            'equipment_preference',
            'genre_distribution',
        ],
        'short_term_rentals' => [
            'property_type_distribution',
            'rental_duration_distribution',
            'price_per_night_distribution',
            'geographic_distribution',
            'amenity_preference',
        ],
        'sports_nutrition' => [
            'product_category_distribution',
            'brand_distribution',
            'price_point_distribution',
            'goal_category_distribution',
            'purchase_frequency',
        ],
        'personal_development' => [
            'course_category_distribution',
            'learning_style_preference',
            'price_point_distribution',
            'completion_rate',
            'skill_level_distribution',
        ],
        'home_services' => [
            'service_type_distribution',
            'task_complexity_distribution',
            'duration_distribution',
            'price_range_distribution',
            'geographic_distribution',
        ],
        'gardening' => [
            'product_category_distribution',
            'seasonal_demand_distribution',
            'price_point_distribution',
            'plant_type_distribution',
            'project_size_distribution',
        ],
        'geo' => [
            'location_query_distribution',
            'geographic_coverage',
            'query_type_distribution',
            'accuracy_requirement',
            'usage_frequency',
        ],
        'geo_logistics' => [
            'route_distance_distribution',
            'delivery_time_distribution',
            'vehicle_type_distribution',
            'geographic_coverage',
            'fuel_efficiency_distribution',
        ],
        'grocery_and_delivery' => [
            'product_category_distribution',
            'order_size_distribution',
            'delivery_time_preference',
            'price_sensitivity',
            'brand_loyalty',
        ],
        'farm_direct' => [
            'product_category_distribution',
            'seasonal_availability_distribution',
            'price_point_distribution',
            'organic_vs_conventional_ratio',
            'geographic_distribution',
        ],
        'meat_shops' => [
            'meat_type_distribution',
            'cut_preference_distribution',
            'price_per_kg_distribution',
            'quantity_distribution',
            'quality_grade_distribution',
        ],
        'office_catering' => [
            'menu_type_distribution',
            'group_size_distribution',
            'price_per_person_distribution',
            'dietary_requirement_frequency',
            'ordering_frequency',
        ],
        'party_supplies' => [
            'product_category_distribution',
            'theme_distribution',
            'group_size_distribution',
            'price_range_distribution',
            'seasonal_demand',
        ],
        'confectionery' => [
            'product_category_distribution',
            'flavor_preference_distribution',
            'price_point_distribution',
            'gift_wrapping_rate',
            'seasonal_demand',
        ],
        'construction_and_repair' => [
            'service_type_distribution',
            'project_size_distribution',
            'duration_distribution',
            'material_cost_distribution',
            'labor_cost_distribution',
        ],
        'cleaning_services' => [
            'service_type_distribution',
            'property_size_distribution',
            'frequency_distribution',
            'price_range_distribution',
            'geographic_distribution',
        ],
        'communication' => [
            'service_type_distribution',
            'usage_pattern_distribution',
            'duration_distribution',
            'cost_distribution',
            'device_preference',
        ],
        'books_and_literature' => [
            'genre_distribution',
            'format_preference_distribution',
            'price_point_distribution',
            'reading_frequency',
            'author_following',
        ],
        'collectibles' => [
            'category_distribution',
            'condition_distribution',
            'price_point_distribution',
            'rarity_distribution',
            'age_distribution',
        ],
        'hobby_and_craft' => [
            'category_distribution',
            'skill_level_distribution',
            'project_complexity_distribution',
            'price_point_distribution',
            'tool_preference',
        ],
        'household_goods' => [
            'product_category_distribution',
            'price_point_distribution',
            'brand_distribution',
            'replacement_frequency',
            'quality_tier_distribution',
        ],
        'marketplace' => [
            'product_category_distribution',
            'price_range_distribution',
            'seller_rating_distribution',
            'shipping_preference',
            'payment_method_distribution',
        ],
        'music_and_instruments' => [
            'instrument_type_distribution',
            'skill_level_distribution',
            'price_point_distribution',
            'genre_preference',
            'brand_distribution',
        ],
        'vegan_products' => [
            'product_category_distribution',
            'certification_preference_distribution',
            'price_point_distribution',
            'brand_distribution',
            'nutritional_focus_distribution',
        ],
        'art' => [
            'medium_distribution',
            'style_distribution',
            'price_point_distribution',
            'collector_segment_distribution',
            'commission_vs_original_ratio',
        ],
    ],
];
