<?php

declare(strict_types=1);

namespace Modules\BigData\Domain\Entities;

use Modules\BigData\Domain\Enums\OptimizationType;
use Modules\BigData\Domain\Enums\RiskLevel;

/**
 * OptimizationRecommendation Entity
 *
 * Immutable domain entity representing a cost optimization recommendation.
 * Auto-generated by the FinOps engine based on cost analysis.
 */
final readonly class OptimizationRecommendation
{
    private function __construct(
        public string $recommendationId,
        public \DateTimeImmutable $createdAt,
        public OptimizationType $type,
        public string $targetResource,
        public string $currentValue,
        public string $recommendedValue,
        public float $estimatedSavingsUsd,
        public float $estimatedSavingsPercent,
        public RiskLevel $riskLevel,
        public string $rationale,
        public string $sqlCommand,
        public string $status,
    ) {
        $this->validate();
    }

    public static function fromAnalysis(
        OptimizationType $type,
        string $targetResource,
        string $currentValue,
        string $recommendedValue,
        float $estimatedSavingsUsd,
        float $estimatedSavingsPercent,
        string $rationale,
        string $sqlCommand = '',
    ): self {
        return new self(
            recommendationId: uniqid('finops_', true),
            createdAt: new \DateTimeImmutable(),
            type: $type,
            targetResource: $targetResource,
            currentValue: $currentValue,
            recommendedValue: $recommendedValue,
            estimatedSavingsUsd: $estimatedSavingsUsd,
            estimatedSavingsPercent: $estimatedSavingsPercent,
            riskLevel: $type->riskLevel(),
            rationale: $rationale,
            sqlCommand: $sqlCommand,
            status: 'pending',
        );
    }

    public function isSafeToAutoApply(): bool
    {
        return $this->riskLevel->isSafeToAutoApply()
            && $this->estimatedSavingsPercent >= 0.05;
    }

    public function toArray(): array
    {
        return [
            'recommendation_id' => $this->recommendationId,
            'created_at' => $this->createdAt->format('c'),
            'type' => $this->type->value,
            'type_display' => $this->type->displayName(),
            'target_resource' => $this->targetResource,
            'current_value' => $this->currentValue,
            'recommended_value' => $this->recommendedValue,
            'estimated_savings_usd' => round($this->estimatedSavingsUsd, 2),
            'estimated_savings_percent' => round($this->estimatedSavingsPercent * 100, 1),
            'risk_level' => $this->riskLevel->value,
            'rationale' => $this->rationale,
            'sql_command' => $this->sqlCommand,
            'status' => $this->status,
            'safe_to_auto_apply' => $this->isSafeToAutoApply(),
        ];
    }

    private function validate(): void
    {
        if ($this->estimatedSavingsUsd < 0) {
            throw new \DomainException('Estimated savings cannot be negative');
        }
        if ($this->estimatedSavingsPercent < 0 || $this->estimatedSavingsPercent > 1) {
            throw new \DomainException('Savings percent must be between 0 and 1');
        }
    }
}
