export { default as BidSubmit } from './BidSubmit.vue'
export { default as PlatformGuarantee } from './PlatformGuarantee.vue'
export { default as SupplierTenderList } from './SupplierTenderList.vue'
export { default as TenderCRMIntegration } from './TenderCRMIntegration.vue'
export { default as TenderCreate } from './TenderCreate.vue'
export { default as TenderCreateFromCRM } from './TenderCreateFromCRM.vue'
export { default as TenderDetail } from './TenderDetail.vue'
export { default as TenderDocuments } from './TenderDocuments.vue'
export { default as TenderList } from './TenderList.vue'
export { default as TenderLotList } from './TenderLotList.vue'
export { default as TenderLotForm } from './TenderLotForm.vue'

export type { Tender, TenderBid, TenderDocument, TenderCreateData, BidCreateData } from '@/services/tenderApi'
export type { TenderLot, TenderBid as CRMTenderBid } from '@/types/crm'
